# Numpy  

## 1. 개념
- Numerical Python
- 파이썬의 고성능 과학 계산용 패키지
- Matrix와 Vector와 같은 Array 연산의 사실상의 표준  

## 2. ndarray
- ndarray: N 차원(Domension) 배열(Array) 객체
- 생성: **arange(), zeros(), ones()**. numpy 모듈의 array() 함수 사용. 인자로 주로 파이썬 list 또는 ndarray 입력 
- 형태와 차원: **ndarray.shape, ndarray.ndim**
- 타입(type): **ndarray.dtype**. ndarray 내의 데이터 값은 숫자 값, 문자열 값, 불 값 등 모두 가능. **ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능** (한 개의 ndarray 개게에 int와 float 같이 있을 수 없음) 
- 타입(type) 변환: **astype()**. 변경을 원하는 타입을 astype()에 인자로 입력. 
- 차원의 크기 변경: **reshape()**. ndarray를 특정 차원 및 형태로 변환. 변환 형태를 함수 인자로 부여.  

## 3. 인덱싱(Indexing)
ndarray의 데이터 세트 선택하기  

### 3.1. 단일 값 추출 
- 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환됨
- ndarrary는 axis를 기준으로 0부터 시작하는 위치 인덱스 값을 가지고 있음
- 마이너스가 인덱스로 사용되면 맨 뒤에서부터 위치를 지정 
- e.g.) 1차원: array1[3], 2차원: array2d[0,1]

### 3.2. 슬라이싱
- 연속된 인덱스 상의 ndarrary를 추출하는 방식임 
- ':' 기호 사용하여 연속된 값 선택. 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1 위치에 있는 ndarrary를 반환함. 
- e.g.) 1차원: array1[0:3], 2차원: array2d[:,1:3]

### 3.3. 팬시 인덱싱
- 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 ndarray 반환함
- e.g.) 1차원: array1[2,4,7], 2차원: array2d[[0,1],0:2]  

### 3.4. 불린 인덱싱 
- 특정 조건에 해당 여부인 T/F 값 인덱싱 집합을 기반으로 T에 해당하는 인덱스 위치에 있는 ndarray 반환함
- 조건 필터링과 검색 동시에 할 수 있음  

# Pandas

## 1. 개념  
- Panel data analysis 혹은 python data analysis의 약자
- "관계형", "테이블 형" 데이터를 만들고 조작하기 위한 파이썬 라이브러리
- NumPy 라이브러리 기반
- 판다스는 행과 열로 이루어진 2차원 데이터를 효율적으로 가공/처리할 수 있는 다양하고 훌륭한 기능을 제공함 
- 여러 장점: 다양한 소스로 입출력, 데이터 조작 용이, 누락 데이터 처리 용이, 통계분석이나 머신 러닝 분석이 가능하도록 연ㄱ 모델을 설정할 수 있음,,, 
- **import pandas as pd**  

## 2. 구성요소 
DataFrame, Series, Index  

### 2.0. 기본 API
**read_csv()**, **head()**, **shape**: 행과 열의 수, **info()**, **describe()**: 기본 통계량 출력 , **value_counts()**, **sort_values()**: 컬럼기준 정렬, **unique()**: 유일한 값 출력  

### 2.1. 변환
- list >> DF: df_list1=pd.DataFrame(list, columns=col_name1)  
- ndarray >> DF: df_array2=pd.DataFrame(array2, columns=col_names2)  
- dict >> DF: dict = {'col1':[1,11], 'col2':[2,22], 'col3':[3,33]} ; df_dict = pd.DataFrame(dict)  
- DF >> ndarray: DF 객체의 Valeus 속성 이용해 ndarray 변환
- DF >> list: DF 객체의 Valeus 속성 이용해 ndarray 변한 후 tolist()이용해 list 변환
- DF >> dict: DF 객체의 to_dict() 이용해 변환 

### 2.2. Index 
- 판다스의 Index 객체는 RDBMS의 PK와 유사하게 DF, Series의 레코드를 **고유하게 식별**하는 개체
- Index 객체만 추출: Data.Frame.index, Series.index
- Series: Index 오직 식별용  

## 3. 기능  

### 3.1. 데이터 셀렉션 및 필터링  
- []: 컬럼 기반 필터링 또는 불린 인덱싱 필터링 제공  
- ix[], loc[], iloc[]: 명칭(Label)/위치(Position) 기반 인덱싱 제공
- 불린 인덱싱: 조건식에 따른 필터링 제공. 

### 3.2. Aggregation 함수 
- sum(), max(), min(), count() 등: DF/Series에서 집합(aggregation) 연산 수행  
- DF의 경우 DF에서 바로 aggregation 호출할 경우 모든 컬럼에 적용  

### 3.3. 결손 데이터(Missing Data) 처리 
- isna(): DF의 isna() 메소드는 주어진 컬럼값이 NaN인지에 대해  T/F 값을 반환함
- fillna(): 결손 데이터를 인자로 주어진 값으로 대체함  

### 3.4. apply lambda 
- 판다스는 apply 함수에 lambda 식을 결합해 DF나 Series의 레코드 별로 데이터를 가공하는 기능 제공 
- 판다스의 경우 컬럼에 일괄적으로 데이터 가공을 하는 것이 속도 면에서 더 빠르나 복잡한 데이터 가공의 경우 어쩔 수 없이 apply lambda를 이용해야함 

-----
# Numpy 기초연습문제

In [1]:
import numpy as np #라이브러리 

## 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [2]:
a = np.zeros((3, 4)) #(행,열)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

In [3]:
for i in range(a.shape[0]):  # for i in :반복문; 이중반복문 
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [4]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

## 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [5]:
a[1, 2]

7.0

## 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

In [6]:
a.shape # ndarray.shape: 형태 확인 

(3, 4)

In [7]:
a[[1], :] #':' 연속

array([[5., 6., 7., 8.]])

## 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

In [8]:
a[:,[0, 2]]

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

## 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

In [9]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])  # 불리안: 조건절 
result

array([1., 2., 3., 4., 5., 6.])

In [10]:
a[a <= 6]

array([1., 2., 3., 4., 5., 6.])

## 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [11]:
b = np.random.random((3, 4))
b

array([[0.72139163, 0.87805504, 0.05714821, 0.99972611],
       [0.693969  , 0.39118094, 0.22539778, 0.31415814],
       [0.94551336, 0.97218012, 0.64593154, 0.45725282]])

## 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [12]:
c = a * b
c

array([[0.72139163, 1.75611008, 0.17144464, 3.99890444],
       [3.46984499, 2.34708564, 1.57778446, 2.51326511],
       [8.50962021, 9.72180122, 7.10524692, 5.48703384]])

## 9. b의 전치행렬을 구하여 d에 저장하시오.

In [13]:
d = b.T # 전치행렬: 행과 열이 바뀐 행렬 
d

array([[0.72139163, 0.693969  , 0.94551336],
       [0.87805504, 0.39118094, 0.97218012],
       [0.05714821, 0.22539778, 0.64593154],
       [0.99972611, 0.31415814, 0.45725282]])

In [14]:
d.shape

(4, 3)

## 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [15]:
print(a.shape, d.shape) # ndarray.shape: 형태 

(3, 4) (4, 3)


## 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [16]:
e = a.dot(d)
e

array([[ 6.64785078,  3.40915677,  6.6566795 ],
       [17.27313474,  9.9079802 , 18.74019085],
       [27.8984187 , 16.40680363, 30.8237022 ]])

## 12. e에 대하여 각 열의 합을 계산하시오.

In [17]:
np.sum(e, axis=1)

array([16.71368706, 45.9213058 , 75.12892454])

---
# Pandas 기초연습문제

In [18]:
import pandas as pd

## 1. 딕셔너리를 이용하여 아래와 같은 모양이 되도록 data frame을 생성하시오.


In [19]:
score={'학번':[201524213,201621223,201621233, 201611111, 201722222],  # 딕셔너리: 'col1':[]
       '이름':['오지환','박용택','정성훈', '다니엘', '지민'],
       '학과':['경영정보','경영정보','경영정보','컴퓨터공학','컴퓨터공학'],
       'Quiz':[15,20,10,17,18],
       '중간고사':[20,20,15,18,16]}

df= pd.DataFrame(score)
df

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
2  201621233  정성훈   경영정보    10    15
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16

In [20]:
df['학번']

0    201524213
1    201621223
2    201621233
3    201611111
4    201722222
Name: 학번, dtype: int64

## 2. 위에서 생성한 데이터프레임으로부터 인덱싱을 이용하여 이름과 중간고사를 추출하시오.

In [21]:
df[['이름', '중간고사']]

이름  중간고사
0  오지환    20
1  박용택    20
2  정성훈    15
3  다니엘    18
4   지민    16

## 3. reindex를 이용하여 2, 0, 4, 1, 3 순으로 순서를 변경하시오.

In [22]:
df = df.reindex([2, 0, 4, 1, 3]) # reindex: 순서 변경 
df

학번   이름     학과  Quiz  중간고사
2  201621233  정성훈   경영정보    10    15
0  201524213  오지환   경영정보    15    20
4  201722222   지민  컴퓨터공학    18    16
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

## 4.  iloc과 loc을 각각 이용하여 박용택 학생의 record를 추출하시오. (iloc으로 한번, loc으로 한번 수행)

In [23]:
print(df.iloc[3])
print(df.loc[1])

학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object
학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object


## 5. iloc과 loc을 각각 이용하여 모든 학생의 이름과 중간고사 점수를 추출하시오. (iloc으로 한번, loc으로 한번 수행)

In [24]:
print(df.iloc[:, [1, 4]])
print(df.loc[:, ['이름', '중간고사']])

    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18
    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18


## 6. 중간고사 점수의 평균을 구하시오.

In [25]:
df['중간고사'].mean() # 평균: mean 

17.8

## 7. 중간고사 점수가 가장 낮은 학생의 index를 구하시오.

In [26]:
df['중간고사'].idxmin() # 최솟값: idxmin()

2

## 8. 퀴즈 점수가 가장 높은 학생의 학번을 구하시오.

In [27]:
df.loc[df['Quiz'].idxmax(), '학번'] # 최댓값: idxmax()
#df.loc[df['Quiz'].idxmax()]['학번']

201621223

## 9. 위 데이터프레임의 각 열에 대해서 개수, 평균, 표준편차, 최소최대값 등의 다양한 통계량을 출력하시오.

In [28]:
df.describe() # 기본 통계량: desxribe() 

학번       Quiz       중간고사
count  5.000000e+00   5.000000   5.000000
mean   2.016200e+08  16.000000  17.800000
std    7.018995e+04   3.807887   2.280351
min    2.015242e+08  10.000000  15.000000
25%    2.016111e+08  15.000000  16.000000
50%    2.016212e+08  17.000000  18.000000
75%    2.016212e+08  18.000000  20.000000
max    2.017222e+08  20.000000  20.000000

## 10. 위 데이터프레임을 중간고사 점수에 따라 내림차순으로 정렬하시오.

In [29]:
df.sort_values('중간고사', ascending=False) # sort_values: 컬럼기준 정렬 

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16
2  201621233  정성훈   경영정보    10    15

## 11. 학생 중에서 퀴즈 점수가 평균 이상인 학생들의 이름을 출력하시오.

In [30]:
quiz_mean = df['Quiz'].mean()
df[df['Quiz'] > quiz_mean]['이름']

4     지민
1    박용택
3    다니엘
Name: 이름, dtype: object

## 12. 학생 중에서 퀴즈와 중간고사 점수 모두 평균 이상인 학생들의 record를 출력하시오

In [31]:
quiz_mean = df['Quiz'].mean()
mid_mean = df['중간고사'].mean()
df[(df['Quiz'] > quiz_mean) & (df['중간고사'] > mid_mean)]

학번   이름     학과  Quiz  중간고사
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

## 13. gvalue_counts를 이용하여 학과 별로 학생의 수를 구하시오.

In [32]:
df['학과'].value_counts() # value_counts(): 개별 컬럼 내 각각의 값이 나온 횟수 출력 

경영정보     3
컴퓨터공학    2
Name: 학과, dtype: int64

## 14. groupby를 이용하여 학과 별로 중간고사의 평균을 구하시오.

In [33]:
df.groupby('학과')['중간고사'].mean()

학과
경영정보     18.333333
컴퓨터공학    17.000000
Name: 중간고사, dtype: float64

In [34]:
df.mean()

학번      201620000.4
Quiz           16.0
중간고사           17.8
dtype: float64

In [35]:
list(df.groupby('학과'))

[('경영정보',
            학번   이름    학과  Quiz  중간고사
  2  201621233  정성훈  경영정보    10    15
  0  201524213  오지환  경영정보    15    20
  1  201621223  박용택  경영정보    20    20),
 ('컴퓨터공학',
            학번   이름     학과  Quiz  중간고사
  4  201722222   지민  컴퓨터공학    18    16
  3  201611111  다니엘  컴퓨터공학    17    18)]